config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  post 'braintree/checkout'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :update, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :listings do
    resources :bookings, only: [:new, :create]
  end

  root "listings#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pairbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Khula|Noto+Sans|Open+Sans" rel="stylesheet">
  </head>

  <body>
    <nav id="navbar" class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar-collapse">
            COLLAPSE
          </button>
          <a class="navbar-brand" href="/">Not AirBnB</a>
        </div>
        <div class="collapse navbar-collapse" id="main-navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Listings", "/listings" %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
              <li><%= link_to "New Listing", "/listings/new" %></li>
              <li><%= link_to current_user.full_name, "/users/#{current_user.id}" %></li>
              <li><%= image_tag(current_user.avatar_url, {class: "profile-pic"}) if current_user.avatar? %></li>
              <li><%= button_to 'Sign out', sign_out_path, method: :delete, id: "sign-out" %></li>
            <% else %>
              <li><%= link_to "Sign in", "/sign_in" %></li>
              <% if Clearance.configuration.allow_sign_up? %>
                <li><%= link_to t(".sign_up"), sign_up_path %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div id="content" class="container-fluid">
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>